version: '3.8'

services:
  web:
    build:
      context: ./study_load
      dockerfile: Dockerfile
    restart: unless-stopped
    command: python manage.py runserver 0.0.0.0:8000
    container_name: web
    volumes:
      - ./study_load/:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    networks:
      - web
    depends_on:
      - db

  db:
    image: mariadb
    container_name: db
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_USER: ${DB_USER}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_HOST: ${DB_HOST}
    volumes:
      - mysql_data:/var/lib/mariadb/data/

    networks:
      - web
volumes:
  mysql_data:


networks:
  web:
    driver: bridge