version: '3.8'

services:
  web:
    build:
      context: ./study_load
      dockerfile: Dockerfile-prod
    command: gunicorn study_load.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
    volumes:
      - static_volume:/home/app/web/staticfiles
  db:
    image: mariadb
    restart: always
    volumes:
      - mysql_data:/var/lib/mariadb/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./nginx
    ports:
      - "1337:80"
    depends_on:
      - web
    volumes:
      - static_volume:/home/app/web/staticfiles
volumes:
  mysql_data:
  static_volume: